### ISSUE TITLE
npm 安装后不能导入

### ISSUE THREAD

**Issue by 2637278968** [laden666666/vue-event-util#1]
导入就报错，
无法找到模块“vue-event-util”的声明文件。“/node_modules/vue-event-util/dist/vue-event-util.js”隐式拥有 "any" 类型。
  Try `npm install @types/vue-event-util` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-event-util';`ts(7016)

**Comment by 2637278968** [comment]
import vueEventUtil from 'vue-event-util'
导入方式

**Comment by laden666666** [comment]
vue-event-util 暂时没有 d.ts 文件，有几种解决方式（其实就是 ts 引入 js 模块的几种方法）：
* 将 noImplicitAny 设置为 true，不过会影响你其他的模块引入。
* 自己补充一个 d.ts 文件，import 前用 reference 注释关联到这个文件
* declare require 函数，让 ts 明白 commonjs 的 API，然后使用 require 引入该库。反正已经打成 bundle 了，tree-shake 肯定会失效的，因此使用 commonjs 引入对你的项目没有任何影响的。
